apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "kube-network-policies.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-network-policies.labels" . | nindent 4 }}
    {{- with .Values.daemonset.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.daemonset.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "kube-network-policies.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kube-network-policies.labels" . | nindent 8 }}
        {{- with .Values.daemonset.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirst
      {{- with .Values.daemonset.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.daemonset.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kube-network-policies.serviceAccountName" . }}
      containers:
        - name: kube-network-policies
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            - /bin/netpol
            - --hostname-override=$(MY_NODE_NAME)
            - --v=2
            {{- if .Values.baselineAdminNetworkPolicy }}
            - --nfqueue-id=99
            - --admin-network-policy=true
            - --baseline-admin-network-policy=true
            {{- else }}
            - --nfqueue-id=98
            {{- end }}
          {{- with .Values.daemonset.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.daemonset.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            {{- with .Values.daemonset.extraEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: lib-modules
              mountPath: /lib/modules
              readOnly: true
      volumes:
        - name: lib-modules
          hostPath:
            path: /lib/modules
