apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-network-policies.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-network-policies.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-network-policies.serviceAccountName" . }}
  labels:
    {{- include "kube-network-policies.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
      {{- if .Values.baselineAdminNetworkPolicy }}
      - nodes
      {{- end }}
    verbs:
      - list
      - watch
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - networkpolicies
    verbs:
      - list
      - watch
  {{- if .Values.baselineAdminNetworkPolicy }}
  - apiGroups:
      - "policy.networking.k8s.io"
    resources:
      - adminnetworkpolicies
      - baselineadminnetworkpolicies
    verbs:
      - list
      - watch
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-network-policies.serviceAccountName" . }}
  labels:
    {{- include "kube-network-policies.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kube-network-policies.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-network-policies.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
